Topic0.1
globant-ui-rosario/evannucci_rosario-web-ui-bootcamp-05-2017 pull request #1
Opened 2017-05-28 20:06 UTC by evannucci

2017-05-28 20:07 UTC, evannucci commented
Topic 0.1

2017-05-29 13:19 UTC, pabloascencao requested changes

2017-05-29 13:19 UTC, pabloascencao commented on 01-HTML-basics/exercise1_html/signup.html
This form has 2 tags with the functionalyti `submit`, there's an input in line 25 and a button in line 39, there's should be just 1 of them.

2017-05-29 22:06 UTC, evannucci commented on 01-HTML-basics/exercise1_html/signup.html
Done !

2017-05-30 12:21 UTC, pabloascencao requested changes

2017-05-30 12:21 UTC, pabloascencao commented on 01-HTML-basics/exercise1_html/table.html
If you want to add a `th` to the table is good to also add a `thead` and a `tbody` for the table body

2017-05-31 01:11 UTC, evannucci commented on 01-HTML-basics/exercise1_html/table.html
Thead and tbody added

2017-05-31 13:53 UTC, pabloascencao approved these changes

2017-06-01 00:26 UTC, merged